EXCLUDE_VERSIONS=3.14.12.5

include ${EPICS_ENV_PATH}/module.Makefile

USR_DEPENDENCIES += asyn,4.31.0
USR_DEPENDENCIES += ethercatlib,e3
USR_DEPENDENCIES += exprtk,1.0.0

# Don't include debug symbols in the binary needed for a debugger
# We don't have a debuuger, so shrink the size from 29MB to 9MB under
# /opt/epics/modules
OPT_CXXFLAGS_YES = -O3

PROJECT=ecmc
# Temporally removed to speed up 
EXCLUDE_ARCHS += eldk

SOURCES = \
  ecmcApp/src/com/cmd.c \
  ecmcApp/src/com/cmd_EAT.c \
  ecmcApp/src/main/gitversion.h \
  ecmcApp/src/main/ecmcError.cpp \
  ecmcApp/src/main/hw_motor.cpp \
  ecmcApp/src/main/ecmcMain.cpp \
  ecmcApp/src/com/ecmcAsynLink.cpp \
  ecmcApp/src/com/ecmcAsynPortDriver.cpp \
  ecmcApp/src/motion/ecmcAxisBase.cpp \
  ecmcApp/src/motion/ecmcAxisData.cpp \
  ecmcApp/src/motion/ecmcAxisReal.cpp \
  ecmcApp/src/motion/ecmcAxisSequencer.cpp \
  ecmcApp/src/motion/ecmcAxisVirt.cpp \
  ecmcApp/src/motion/ecmcCommandTransform.cpp \
  ecmcApp/src/motion/ecmcDriveBase.cpp \
  ecmcApp/src/motion/ecmcDriveDS402.cpp \
  ecmcApp/src/motion/ecmcDriveStepper.cpp \
  ecmcApp/src/motion/ecmcEncoder.cpp \
  ecmcApp/src/motion/ecmcFilter.cpp \
  ecmcApp/src/motion/ecmcMasterSlaveData.cpp \
  ecmcApp/src/motion/ecmcMasterSlaveIF.cpp \
  ecmcApp/src/motion/ecmcMonitor.cpp \
  ecmcApp/src/motion/ecmcPIDController.cpp \
  ecmcApp/src/motion/ecmcTrajectoryTrapetz.cpp \
  ecmcApp/src/misc/ecmcCommandList.cpp \
  ecmcApp/src/misc/ecmcDataRecorder.cpp \
  ecmcApp/src/misc/ecmcDataStorage.cpp \
  ecmcApp/src/misc/ecmcEventConsumer.cpp \
  ecmcApp/src/misc/ecmcEvent.cpp \
  ecmcApp/src/ethercat/ecmcEc.cpp \
  ecmcApp/src/ethercat/ecmcEcEntry.cpp \
  ecmcApp/src/ethercat/ecmcEcEntryLink.cpp \
  ecmcApp/src/ethercat/ecmcEcMemMap.cpp \
  ecmcApp/src/ethercat/ecmcEcPdo.cpp \
  ecmcApp/src/ethercat/ecmcEcSDO.cpp \
  ecmcApp/src/ethercat/ecmcEcSlave.cpp \
  ecmcApp/src/ethercat/ecmcEcSyncManager.cpp \
  ecmcApp/src/plc/ecmcPLC.cpp \
  ecmcApp/src/plc/ecmcPLCDataIF.cpp \
  ecmcApp/src/plc/ecmcPLCs.cpp \
